### PR TITLE
E2E tests

### PR DESCRIPTION
**Pull request by davidhadas**
e2e tests. 

First, a complete knative environment for e2e testing is created with kourier and DNS support + kn
Log level is set to debug
Than the security-guard is installed.

The guardian for the `httptest` service is loaded.
kn is used to add the `httptest` service which is protected by security-guard.

Minimalistics 3 bash-based tests. 

1. Simple `curl` with no query, no special header - allowed by the guardian => confirm that no alert is logged
2. Simple `curl` with a new query key-  not allowed by the guardian => alert is logged
3. Simple `curl` with a new header - not allowed by the guardian => alert is logged

Also fixes a bug found in service-account role binding.

### CODE REVIEW

**Comment by psschwei** [comment]
Doesn't look like the e2e tests ran...

**Comment by davidhadas** [comment]
I think they need to first merge to main, then you will be able to run them using a manual trigger. 

Maybe you can see it on my fork at davidhadas. 

On my fork, I needed to merge the test to main before I can run it.

**Comment by psschwei** [comment]
> I think they need to first merge to main, then you will be able to run them using a manual trigger.
 
any specific reason to prefer a manual trigger vs. on all PRs?

**Comment by davidhadas** [comment]
> > I think they need to first merge to main, then you will be able to run them using a manual trigger.
>  
> any specific reason to prefer a manual trigger vs. on all PRs?

One step at a time 🤷‍♂️
To see it is stable...

If you feel it is better to immidiatly trigger it with each PR, we can do that.

**Comment by psschwei** [comment]
I'd lean towards waiting to merge until we're reasonably sure it's stable (and we can run it a bunch against this PR to get a sense of that). Let's update to run on all PRs.

**Review by psschwei — COMMENTED** [review]
/lgtm
/hold

@davidhadas e2e tests have run 20 times without issue. I'm good with merging them, but putting a hold in case you want to rerun them some more. Feel free to cancel the hold if/when you see fit.

**Comment by davidhadas** [comment]
> /lgtm
> /hold
> 
> @davidhadas e2e tests have run 20 times without issue. I'm good with merging them, but putting a hold in case you want to rerun them some more. Feel free to cancel the hold if/when you see fit.

/unhold

**Pull request merged**
