### PR TITLE
Improved Scripts and Logs

### PR DESCRIPTION
**Pull request by davidhadas**
1. Improved and simplified scripts
2. Added guard-service setup in scripts
3. Improved logs and reduced INFO noise
4. Changed default log level of guard-service to info

Will be cherrypicked to 0.3

### CODE REVIEW

**Comment by davidhadas** [comment]
/hold
About to add a log entry to spell out if guard-gate uses TLS and Token or not

**Review by psschwei — COMMENTED** [review]
/lgtm

**Pull request merged**
