### PR TITLE
Authenticate guard-service requests

### PR DESCRIPTION
**Pull request by davidhadas**
Fix: #71 
# Changes
1. Extract a jwt token from Authorization Bearer 
2. Validate Token using KubeAPI
3. Parse token and find podname and ns
4. Get pod info from KubeAPI and extract the sid (service ID) from pod labels  - the `serving.knative.dev/service` or `app` 
5. This replaces the sid and ns  being provided via the query string

### CODE REVIEW

**Comment by davidhadas** [comment]
/hold
Rethink since we dont have such support in knative
Make token support optional - use it only if we have it.
Maybe add config param to determine of service should mandate it or not

**Comment by davidhadas** [comment]
/unhold
Added token support as a config param

**Comment by davidhadas** [comment]
The CodeQL screams since he does not support the detection of in-place sanitization which is what we do. 
Instead he assumed no sanitization was done and alerts

**Review by psschwei — COMMENTED** [review]
/lgtm

**Pull request merged**
