### PR TITLE
get repo in order

### PR DESCRIPTION
**Pull request by davidhadas**
fix links
add image

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
Question on the guard image: did you create that yourself?

**Comment by davidhadas** [comment]
https://pixabay.com/illustrations/male-fantasy-character-medieval-4955787/
See License

**Comment by psschwei** [comment]
I think that's probably ok, but let's get the ok from @knative-sandbox/steering-committee just to be safe

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
