### PR TITLE
[WIP]  - Previous version: Second v1alpha1 commit with SimpleVal

### PR DESCRIPTION
**Pull request by davidhadas**
In this PR we review the DataType used most by Guard - the SimpleVal

SimpleVal represents a simple textual value, used for:
 - URL
 - One Value of an HTTP Header
 - One Value from a QueryString
 - A Key of a header (The header name)
 - A Key for a query string
 - A json/form value  sent to in the body 
 - A json/form key  sent to in the body 
 (I may heve missed some)
 
 SimpleVal uses Count for holding counters, asciiFalgs to understand the security-related content of the evaluated string and unicodeFlags to  understand the Unicode content of SimpleVal.

### CODE REVIEW

**Comment by davidhadas** [comment]
@evankanderson [added a comment on PR/9 as it was merging](https://github.com/knative-sandbox/security-guard/pull/9#issuecomment-1218358339):
> Looking at 16, it seems like we have the following setup:
> 
> * `XXProfile` is a concrete type which interprets `Profile()` specially for each type.
> * `XXPile` is a "collection" of `XXProfile` objects. In some cases, there is an optimized mechanism for merging the profiles (equivalent to a "set", but often using bitmaps); the default is to simply collect them in a slice.  In particular, I can imagine a future algorithm which is concerned about the _frequency_ of profiles in a pile, so optimizing this to a "set" is probably not a good idea -- a histogram might be acceptable, but "collection" seems about the right scope. 

Yep, certainly agree. 
The choice to pile asciiFlags as bitmap `type AsciiFlagsPile uint32` and not in a slice `type AsciiFlagsPile []uint32` is an optimization. We can decide to remove this optimization. And indeed, since we are later learning based on piles, **this will be an advantage**.  Piles are being collected in QP instances and later sent to a remote service, removing such optimization somewhat increases the size of the delivered message.   

The same is true for flagsSlice, but since flagsSlice depends on the Unicode used, the size of the slice really depends on the Unicode blocks used by the application. For English, this will be empty. For the Chinese lang, it could be in theory some 24K bytes (I am sure in practice the blocks used are mapped earlier in the Unicode tables). We need a Chinese lang expert here to tell us if these late Unicode blocks are in use... 

E.g. if we have N samples, given the current optimization, a pile size will be: `N + 4 + 0..24K + json overhead`
Without asciiFlag optimization, it will be: `5*N + 0..24K + json overhead`
And without Unicode optimization, it will be `(5 + 0..24K)*N + json overhead`

So right now Guard is optimized to limit the growth of piles - i.e. support many requests in a reasonable compromise on losing information of value to security by making an early merging of flags as shown in asciiFlags and flagsSlice.

The analogy to a collection breaks when you look at SimpleVal and any composite DataType that will follow. SimpleValPile is not a collection of SimpelVals - it is a struct of size 6 CountPiles, 1 AsciiPile, and 1 FlagsSclicePile.  

> * `XXConfig` performs profile-specific operations for `Decide` and `Learn` as well as `Fuse` (though I don't see why `Fuse` is needed at the moment).

Think of Config as maintaining what was learned. Fuse is needed since at some later point we will see that whatever you learned now, needs to be fused with what you learned earlier. 

> 
> I wonder whether making `Pile` a generic interface which collects in a slice with an _optional_ `Coalesce` method on `XXProfile` would work:
> 
> https://go.dev/play/p/bpzlStlyhB5

`func (ps *Pile[T]) add(v T) ` can help us have a single implementation for all Piles that use append to a slice. 
For this, it is a useful construct. Right now this does not allow aligning any type as only Count use this method and 13 others use other methods. If we move to AsciiPile based on a slice of uint32, we will have 2 out of 14 that can use this construct.

Hence generics may offer us some value but not change the need for runtime type assertions or simplify our implementation as a whole.

**Comment by evankanderson** [comment]
> @evankanderson [added a comment on PR/9 as it was merging](https://github.com/knative-sandbox/security-guard/pull/9#issuecomment-1218358339):
> > Looking at 16, it seems like we have the following setup:
> > ...
> > I wonder whether making `Pile` a generic interface which collects in a slice with an _optional_ `Coalesce` method on `XXProfile` would work:
> > 
> > https://go.dev/play/p/bpzlStlyhB5
> 
> `func (ps *Pile[T]) add(v T) ` can help us have a single implementation for all Piles that use append to a slice. 

It seems like it _at least_ also covers AsciiPile and FlagPile with the `Combine` method, but I think `Combine` may be suitably general given the slice-in, slice-out contract.

See the example with `Proc` which defines a `Combine` method where the length of the slice is never greater than 2, and is 1 except during `add`.

There's more you could do to optimize memory allocation, but I didn't feel like writing a benchmark and tuning the structures at this point.

In terms of SimpleVal, you may want to consider whether seven CountVals is the best representation, or whether a (sparse) map is better. This is where a benchmark and actual data would be handy. 😁

> Hence generics may offer us some value but not change the need for runtime type assertions or simplify our implementation as a whole.

I think the pattern of defining a type-checked interface (possibly including `Learn` and `Decide`) using generics, and then defining specialized implementations not using generics may be helpful in avoiding type confusion.

At the very least, it feels like the `Pile` and `Config` _interfaces_ should use generics so you can't accidentally feed a `FooPile` to a `BarConfig`.

**Comment by evankanderson** [comment]
Vis-a-vis the separation of `XXPile` objects from `XXConfig` objects, I assume that conceptually you end up at some point with many Piles waiting to be merged into the Config? If there's only a single Pile outstanding, it might be simpler to manage it inside the Pile.

I'm also wondering whether the var-args nature of `Profile` is needed -- the current examples all seem to select the first element and then type-coerce it to the underlying type. Furthermore, none of the Pile/Config interfaces seems to depend on the Profile method, so a simple constructor might make more sense.

**Comment by davidhadas** [comment]
It is correct that maycurrent DataTypes accept a single arg to Profile(). 
There have been variants with more than one arg and still, there is at least one with 3 (and one that does not accept any args and Profile the data based on exploring the POD status). This area will evolve, if we have a clear benefit from a single arg, maybe we need to standardize on that and require profiles that need multiple args to pack them in a struct.

**Comment by davidhadas** [comment]
See https://github.com/knative-sandbox/security-guard/pull/20 for an alternative that uses compile-time type checking (takes advantage of golang as a striclly typed lag.).

**Comment by evankanderson** [comment]
I guess I'm trying to figure out the interface benefit to including `Profile(args ... interface)` in the actual interface contact -- it seems like each type ends up assuming different actual arguments, so it's not like `Profile(context.Context)` or `Profile(https.Request)` where you expect each impending type to know how to extract data from a common argument.

**Comment by davidhadas** [comment]
> I guess I'm trying to figure out the interface benefit to including `Profile(args ... interface)` in the actual interface contact -- it seems like each type ends up assuming different actual arguments, so it's not like `Profile(context.Context)` or `Profile(https.Request)` where you expect each impending type to know how to extract data from a common argument.

It allows:
1. common testing
2. ensures that every DATATYPE has an object with a Profile() method 
3. ensures that this object is what is fed to Pile.Add() 
4. ensures that this object is what is fed to Config.Decide()
Please see the alternative in PR/20 - from your comments, it seems like a compromise you will like better. 
 
 I can testify from experience in the previous version that maintaining many DATATYPEs, each with Profile, Pile, and Config and without the help of a common interface results in divergence and makes it harder to maintain. I do expect more DATATYPEs added over time ad existing DATATYPEs evolve, so we need to do what we can when we can to maintain this common contract between DATATYPEs.

**Comment by davidhadas** [comment]
/hold
We will probably close this without merging - instead, we will merge PR/20 - a waiting final decision

**Comment by psschwei** [comment]
Going with #20 instead

**Pull request closed without merging**
